# DataRoot University DS100 Test #2
На проходження тесту виділяється 100 і одна хвилина.

## Python

### 1.  Реалізуйте функцію для видалення дублікатів зі списку списків:
У відповідь вивести результат роботи ф-ції для наступного списку:
```
[[10, 20], [40], [30, 56, 25], [10, 20], [33], [40], [42], [10, 42], [42]]
```


```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [2]:
def delete_duplications (l):
    new_l = []
    for el in l:
        if el not in new_l:
            new_l.append(el)
        else:
            continue
    return new_l

l = [[10, 20], [40], [30, 56, 25], [10, 20], [33], [40], [42], [10, 42], [42]]
delete_duplications (l)

[[10, 20], [40], [30, 56, 25], [33], [42], [10, 42]]

### 2.  Реалізуйте функцію str -> dict, таку, що ключем dict є символ строки, а значенням - його кількість в початковій str:
У відповідь вивести результат роботи ф-ції для наступної строки:
```"DataRoot University DS100 Test #2"```

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [5]:
def str_to_dict(s):
    d = {char: s.count(char) for char in s}
    return d

s = "DataRoot University DS100 Test #2"
str_to_dict(s)

{' ': 4,
 '#': 1,
 '0': 2,
 '1': 1,
 '2': 1,
 'D': 2,
 'R': 1,
 'S': 1,
 'T': 1,
 'U': 1,
 'a': 2,
 'e': 2,
 'i': 2,
 'n': 1,
 'o': 2,
 'r': 1,
 's': 2,
 't': 4,
 'v': 1,
 'y': 1}

### 3. Реалізуйте функцію, яка приймає два параметри: к-сть голів та к-сть ніг. За допомогою цієї функції вирішити наступну проблему: ми нарахували 35 голів та 94 ніг серед курей та кроликів на фермі. Скільки кроликів і скільки курей ми маємо?

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 7хв
```

In [9]:
def farm (head, legs):
    #c + r = head
    #2c + 4r = legs
    #c + 2r = legs//2
    #c + r + r = legs//2
    #head + r = legs // 2
    #r = legs // 2 - head
    #c = head - r
    r = legs // 2 - head
    c = head - r
    answer = "На фермі " + str(r) + " кроликів і " + str(c) + " курки"
    return answer

farm (35, 94)

'На фермі 12 кроликів і 23 курки'

### 4. Реалізуйте клас під назвою Circle, побудований за радіусом та містить два способи, які обчислюють площу та периметр.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [18]:
class Circle:
    def __init__(self, radius):
        self.radius = radius
        
    def area (self, radius):
        a = 3.14*(radius**2)
        return a
    
    def perimeter (self, radius):
        p = 2*3.14*radius
        return p
    
my_circle = Circle(10)
print(my_circle.area(10))
print(my_circle.perimeter(10))
    

314.0
62.800000000000004


### 5.  Реалізуйте декоратор, який логує аргументи функцій та повернене значення кожного виклику. Необхідно виводити як позиційні(```*args```), так й іменовані аргументи(```**kwargs```):

Приклад застосування вашого декоратору в результаті:
```
>>> @log
... def func(*args):
...   return len(args)
>>> func(4, 4, 4)
you called func(4, 4, 4)
it returned 3
3
```

```
```
```
```
```
```
```
Максимальна оцінка: 4 бали
Рекомендований час: 15хв
```

## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Розв'яжіть систему рівнянь:


\begin{equation*}
 \begin{cases}
   x + y - z + 2 = 0
   \\
   3x - y + 2z - 9 = 0
   \\
   4x + 4y - 3z + 5 = 0
 \end{cases}
\end{equation*}

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [24]:
import numpy as np

a = np.array([[1, 1, -1], [3, -1, 2], [4, 4, -3]])
b = np.array([-2, 9, -5])
x = np.linalg.solve(a, b)
print("Solution: ", x)
if a.dot(x).all() == b.all():
    print("Solution is correct")


Solution:  [ 1.  0.  3.]
Solution is correct


### 7. Дана матриця:
\begin{align}
A = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}
Знайти:

#### 7.1. Транспоновану: $A^{-1}$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [26]:
a = np.array([[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [4, 6, 13, 20, 22], [10, 12, 19, 21, 3], [11, 18, 25, 2, 9]])
b = np.transpose(a)
print("Transposed: ", b)

Transposed:  [[17 23  4 10 11]
 [24  5  6 12 18]
 [ 1  7 13 19 25]
 [ 8 14 20 21  2]
 [15 16 22  3  9]]


#### 7.2. Детермінант: $\det A$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 7.3. Слід: $\DeclareMathOperator{\tr}{Tr}\tr A$
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 7.4. Доказати, що матриця А є магічним квадратом.
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

### Pandas

### 8. Розглянемо наступний словник ```data``` та список ```labels```:

In [57]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

#### 8.1. Створіть ```DataFrame``` ```df``` з даних словника ```data``` з індексами зі списку ```labels```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 8.2. Відобрзіть базову інформацію про цей ```DataFrame``` та його дані:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 8.3. Поверніть перші 3 рядки ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 8.4. Виберіть стовпчики ```"animal"``` та ```"age"``` з ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 8.5 Виберіть дані з рядків ```[3, 4, 8]``` та стовпчиків ```['animal', 'age']```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 8.6. Виберіть лише ті рядки, в яких к-сть візитів більша ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 8.7. Виберіть рядки, де вік відсутній, тобто ```NaN```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 8.8. Виберіть рядки з котами, вік яких менше ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 8.9. Підрахуйте середній вік для кожного з типів тварин:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 4хв
```

#### 8.10. Відсортуйте ```df``` по-перше за віком в спадаючому порядку, по-друге за к-стю візитів в зростаючому порядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 4хв
```

#### 8.11. В ```'animal'``` ствобчику, змініть всіх ```'snake'``` на ```'python'```:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 4хв
```

## Scipy & Matplotlib

### 9. За допомогою scipy згенерувати та за допомогою matplotlib побудувати вибірки, правильно підписавши осі та назвавши графік з обраними відповідними параметрами:

#### 9.1. Виібрку з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.2. Вибірку з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.3. Вибірку з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.4. Вибірку з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```