# DataRoot University DS100 Test #2
На проходження тесту виділяється 87 хвилин.

## Python

### 1.  Реалізуйте функцію, яка повертає індекс кортежу, сума елементів якого є найбільшою серед кортежів в списку:
У відповідь вивести результат роботи ф-ції для наступного списку:
```
[(10, 20), (40), (30, 56, 25), (10, 20), (33), (40), (42), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
```


```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [1]:
def delete_duplications (l):
    new_l = []
    for el in l:
        if el not in new_l:
            new_l.append(el)
        else:
            continue
    return new_l

l = [[10, 20], [40], [30, 56, 25], [10, 20], [33], [40], [42], [10, 42], [42]]
delete_duplications (l)

[[10, 20], [40], [30, 56, 25], [33], [42], [10, 42]]

### 2.  Реалізуйте функцію str -> dict, таку, що ключем dict є слово, а значенням - його кількість в початковій str:
У відповідь вивести результат роботи ф-ції для наступної строки:
```"Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text. High-quality information is typically derived through the devising of patterns and trends through means such as statistical pattern learning. Text mining usually involves the process of structuring the input text (usually parsing, along with the addition of some derived linguistic features and the removal of others, and subsequent insertion into a database), deriving patterns within the structured data, and finally evaluation and interpretation of the output. 'High quality' in text mining usually refers to some combination of relevance, novelty, and interestingness."```

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [6]:
def str_to_dict(s):
    new_s = s.split(" ")
    d = {char: s.count(char) for char in new_s}
    return d

s = "Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text. High-quality information is typically derived through the devising of patterns and trends through means such as statistical pattern learning. Text mining usually involves the process of structuring the input text (usually parsing, along with the addition of some derived linguistic features and the removal of others, and subsequent insertion into a database), deriving patterns within the structured data, and finally evaluation and interpretation of the output. 'High quality' in text mining usually refers to some combination of relevance, novelty, and interestingness."
str_to_dict(s)

{"'High": 1,
 '(usually': 1,
 'High-quality': 1,
 'Text': 2,
 'a': 47,
 'addition': 1,
 'along': 1,
 'also': 1,
 'analytics,': 1,
 'and': 6,
 'as': 3,
 'combination': 1,
 'data': 3,
 'data,': 1,
 'database),': 1,
 'derived': 2,
 'deriving': 2,
 'devising': 1,
 'equivalent': 1,
 'evaluation': 1,
 'features': 1,
 'finally': 1,
 'from': 1,
 'high-quality': 1,
 'in': 28,
 'information': 2,
 'input': 1,
 'insertion': 1,
 'interestingness.': 1,
 'interpretation': 1,
 'into': 1,
 'involves': 1,
 'is': 5,
 'learning.': 1,
 'linguistic': 1,
 'means': 1,
 'mining': 4,
 'mining,': 2,
 'novelty,': 1,
 'of': 7,
 'others,': 1,
 'output.': 1,
 'parsing,': 1,
 'pattern': 3,
 'patterns': 2,
 'process': 2,
 "quality'": 1,
 'referred': 1,
 'refers': 1,
 'relevance,': 1,
 'removal': 1,
 'roughly': 1,
 'some': 2,
 'statistical': 1,
 'structured': 1,
 'structuring': 1,
 'subsequent': 1,
 'such': 1,
 'text': 5,
 'text.': 1,
 'the': 9,
 'through': 2,
 'to': 4,
 'trends': 1,
 'typically': 1,
 'usually': 3,
 'w

### 3. Спортсмен почав тренування, пробігши в перший день N км (N - ціле). Кожен наступний день він збільшував дистанцію пробігу на Р відсотків від дистанції пробігу попереднього дня(Р - дійсне, 0 < P < 50). По заданим Р, N, M, визначити, після якого дня сумарний пробіг спортсмена за всі дні буде вперше більшим, ніж M км (М - ціле, M > N). Вивести знайдену кількість днів К (K - ціле) і сумарний пробіг за К днів.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 7хв
```

### 4. Реалізуйте клас під назвою Triangle, побудований за трьома сторонами та містить два методи: обчислення площі та периметру.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [23]:
import math
class Triangle:
    def __init__ (self, a, b, c):
        self.a = a
        self.b = b
        self.c = c
        
    def perimeter(self, a, b, c):
        return self.a + self.b + self.c
    
    def square (self, a, b, c):
        p = self.perimeter(a, b, c)/2
        s = math.sqrt(p*(p-a)*(p-b)*(p-c))
        return s

my_triang = Triangle(3, 4, 5)
print(my_triang.perimeter(3, 4, 5))
print(my_triang.square(3, 4, 5))

12
6.0


### 5.  Реалізуйте декоратор, який логує аргументи функцій та повернене значення кожного виклику. А при помилковому виклику відловлює та пише тип помилки. Необхідно виводити як позиційні(```*args```), так й іменовані аргументи(```**kwargs```):

Приклад застосування вашого декоратору в результаті:
```
>>> @log
... def func(*args):
...   return len(args) + sum(args)
>>> func(4, 4, 4)
You called func(4, 4, 4)
It returned 15
15

>>> func(4, 4, "4")
You called func(4, 4, "4")
It Raised TypeError
```

```
```
```
```
```
```
```
Максимальна оцінка: 4 бали
Рекомендований час: 15хв
```

## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Дана матриця:
\begin{align}
A = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}


#### Відніміть середнє арифметичне кожного рядку від кожного елементу у відповідному рядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [6]:
import numpy as np
a = np.array([[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [4, 6, 13, 20, 22], [10, 12, 19, 21, 3], [11, 18, 25, 2, 9]])
mean = np.mean(a, axis = 0)
a = a - mean
print(a)


[[  4.  11. -12.  -5.   2.]
 [ 10.  -8.  -6.   1.   3.]
 [ -9.  -7.   0.   7.   9.]
 [ -3.  -1.   6.   8. -10.]
 [ -2.   5.  12. -11.  -4.]]


### 7. Дано наступні матриці:
\begin{align}
A = \begin{bmatrix}
    1 & 24 & 1 & 8 & 15 \\
    -3 & 5 & 7 & -14 & 16 \\
    4 & 6 & -3 & 20 & 2 \\
    10 & 12 & 19 & 21 & 3 \\
    1 & 1 & 2 & -2 & 0 \\
\end{bmatrix}
\end{align}
\begin{align}
\end{align}
\begin{align}
B = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}
Знайти:

#### 7.1. $(A B)^{-1}B$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [ ]:
a = np.array([[1, 24, 1, 8, 15], [-3, 5, 7, -14, 16], [4, 6, -3, 20, 2], [10, 12, 19, 21, 3], [1, 1, 2, -2, 0]])
b = np.array([[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [4, 6, 13, 20, 22], [10, 12, 19, 21, 3], [11, 18, 25, 2, 9]])
ab = a.dot(b)

#### 7.2. Детермінант: $\det ((A B)^{-1}B)$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 7.3. Нормалізуйте: $(A B)^{-1}B$
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 7.4. Змініть матрицю B таким чином, щоб всі елементи k, такі що 3 < k < 16, змінили знак.
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

### Pandas

### 8. Розглянемо наступний словник ```data``` та список ```labels```:

In [1]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

#### 8.1. Створіть ```DataFrame``` ```df``` з даних словника ```data``` з індексами зі списку ```labels```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.2. Відобразіть базову інформацію про цей ```DataFrame``` та його дані:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.3. Поверніть перші 3 рядки ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.4. Виберіть стовпчики ```"animal"``` та ```"age"``` з ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.5 Виберіть дані з рядків ```[3, 4, 8]``` та стовпчиків ```['animal', 'age']```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.6. Виберіть лише ті рядки, в яких к-сть візитів більша ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.7. Виберіть рядки, де вік відсутній, тобто ```NaN```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.8. Виберіть рядки з котами, вік яких більше ніж 2:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 8.9. Підрахуйте середній вік для кожного з типів тварин:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 8.10. Відсортуйте ```df``` по-перше за віком в спадаючому порядку, по-друге за к-стю візитів в зростаючому порядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 8.11. Стовпець "priority" містить значення "yes" та "no". Замінити цей стовпець стовпчиком булевих значень: "yes" на True, а "no" на False:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

## Scipy & Matplotlib

### 9. За допомогою scipy згенерувати та за допомогою matplotlib побудувати функцію розподілу ймовірностей для вибірок, правильно підписавши осі та назвавши графік з обраними відповідними параметрами:

#### 9.1. Для виібрки з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.2. Для вибірки з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.3. Для вибірки з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.4. Для вибірки з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```